pipeline {
    agent any

    stages {
        stage("Checkout") {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PerBuildTag'], [$class: 'PathRestriction', excludedRegions: 'docs/.*', includedRegions: '']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github_login', url: 'https://github.com/songguoqiang/gradle-monorepo-demo.git']]])
            }
        }
        stage('Build') {
            steps {
                echo 'Building Greeter..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing Greeter..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying Greeter....'
            }
        }
    }
}