pipeline {
    agent any

    stages {
//         stage("Checkout") {
//             steps {
//                 checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'PerBuildTag'], [$class: 'PathRestriction', excludedRegions: '', includedRegions: '''greeter/.*
// greeting-library/.*''']], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github_login', url: 'https://github.com/songguoqiang/gradle-monorepo-demo.git']]])
//             }
//         }
        stage('Build') {
            steps {
                echo 'Building Greeter..'
            }
        }
        stage('Test') {
            steps {
                sh "./gradlew clean test"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying Greeter....'
            }
        }
    }

     post {
       always {
         publishHTML([reportDir: 'greeter/build/reports/tests/test', reportFiles: 'index.html', reportName: 'Greeter Test Report'])
       }
    }
}